spring:
  application:
    name: geofences

  datasource:
    url: jdbc:postgresql://localhost:5432/geofences

  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
